---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang
    commands:
      - go get
      - go test  
  - name: build
    image: golang
    commands:
      - go get
      - go build -o output
      - chmod +x output  
  - name: build2
    image: golang
    environment:
      A_SECRET:
        from_secret: a_secret
    commands:
    - echo $$A_SECRET
    - go run . > test_secret.txt
    - cat test_secret.txt
  - name: deploy
    image: golang
    commands:
      - go get
      - go build -o output
      - chmod +x output
      - ./output

